# 점수, 사번, 성명, 직책, 이메일
SELECT 
       SUM(SCORE) AS SCORE,
       A.EMP_NO,
       A.EMP_NAME,
       A.POSITION,
       A.EMAIL
  FROM HR_EMPLOYEES A
  JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
 WHERE YEAR = 2022
 GROUP BY EMP_NO
 ORDER BY SCORE DESC
 LIMIT 1;