SELECT
       A.BOOK_ID,
       B.AUTHOR_NAME,
       left(A.PUBLISHED_DATE,10) AS PUBLISHED_DATE
  FROM BOOK A
  JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
 WHERE A.CATEGORY = "경제"
 ORDER BY A.PUBLISHED_DATE
  